name: torcher
description: Flashlight Torcher - Yet another torch/flashlight/lamp app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# A version number is three numbers separated by dots, like 1.2.43
# In Android, build-name is used as versionName while build-number used as versionCode.
version: 1.2.0+3

environment:
  sdk: ">=2.16.0-80.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  torch_control: ^0.4.0           # phone light control
  vibration: ^3.1.3               # phone vibration
  url_launcher: ^6.3.0            # launch an url (web, email, ...)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

  assets:
    - assets/app/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app/icon.png"
